Switch to bun in replit setup
replit/codemirror-minimap pull request #31
Opened 2023-10-21 01:46 UTC by bradymadden97

y not :) 

Test:
clicked the run button and things seemed to work

2023-10-21 01:46 UTC, bradymadden97 commented on package.json
> +    "@codemirror/language": "^6.9.1",
This just keeps happening automatically, i feel like nobody supports peer dependencies correctly or maybe it's a bug on our side, but I'm just going to roll with it at this point.

2023-10-21 02:05 UTC, masad-frost commented on package.json
> +    "@codemirror/language": "^6.9.1",
Things under `dependencies` get installed when you install the package that specifies them as transient dependencies. Then when module resolver sees your import, it will use the version specified by this package, not the one specified by the consumer.

This will lead to issues like "looks like you're using multiple instances of EditorState"..etc

Let's use peer dependencies.

2023-10-21 02:07 UTC, masad-frost commented on package.json
> +    "@codemirror/language": "^6.9.1",
You should specify the dependencies you're using in development under devDependencies so that they're installed when you're developing, then list the that are needed with the package under dependencies.

2023-10-21 02:08 UTC, masad-frost commented on package.json
> +    "@codemirror/language": "^6.9.1",
For example https://github.com/replit/Codemirror-CSS-color-picker/blob/master/package.json#L25-L40

2023-10-21 02:09 UTC, masad-frost requested changes
no deps pls

2023-10-21 02:11 UTC, masad-frost commented on package.json
> +    "@codemirror/language": "^6.9.1",
this is the codemirror error i'm referring to https://github.com/codemirror/state/blob/10d5f42d5b785e80a4262536703c4aabea6126b9/src/facet.ts#L544

but even if you don't hit that error, you'll likely hit undefined state

2023-10-21 02:13 UTC, masad-frost commented
Otherwise this is great :)

2023-10-21 02:14 UTC, masad-frost commented on package.json
> +    "@codemirror/language": "^6.9.1",
> i feel like nobody supports peer dependencies correctly or maybe it's a bug on our side

Thought I'd clarify further, peerDependencies are never installed (they're just hints) hence my comment https://github.com/replit/codemirror-minimap/pull/31#discussion_r1367601307

2023-10-21 04:34 UTC, masad-frost commented
readme references minimap pnpm btw

2023-10-23 03:46 UTC, bradymadden97 commented on package.json
> +    "@codemirror/language": "^6.9.1",
Good call this seems to have fixed the issues I had earlier (by duplicating them into dev deps).

2023-10-25 22:59 UTC, bradymadden97 commented
bump

2023-10-25 23:14 UTC, masad-frost approved these changes
a lil' spooky due to bun not having 100% compatibility with v8, but what's the worst that can happen!

2023-10-26 01:50 UTC, bradymadden97 commented
where do you see issues arising? discrepancy in dev, or prod build?
- dev i guess maybe is a possibility. it's using the vite plugin for bun iirc, so I assumed vite behavior would be the same but could be wrong
- prod it's not actually using bun to build - I'm using marijn's codemirror build scripts.

2023-10-26 01:51 UTC, merged

2023-10-26 21:47 UTC, masad-frost commented
Dev is fine

> I'm using marijn's codemirror build scripts.

I mean if that has a node shebang, then it would be fine. Otherwise we're gonna be using bun runtime.

2023-10-26 21:48 UTC, masad-frost commented
I guess i don't see issues arising because the build output doesn't care about the runtime used at build time, but maybe there's an off chance that we get a corrupt build because something in the runtime is different. Unlikely.